### WHOAMI
GET  https://api.printnode.com/whoami HTTP/1.1
Authorization: Basic User:WJvzmkJLpB_PBDTVEoNR7Bfwe0khKhU33KBB-Cvxus4
###
GET  https://api.printnode.com/printers HTTP/1.1
Authorization: Basic User:WJvzmkJLpB_PBDTVEoNR7Bfwe0khKhU33KBB-Cvxus4
###
GET  https://api.printnode.com/computers HTTP/1.1
Authorization: Basic User:WJvzmkJLpB_PBDTVEoNR7Bfwe0khKhU33KBB-Cvxus4
###
POST  https://api.printnode.com/printjobs HTTP/1.1
Authorization: Basic User:WJvzmkJLpB_PBDTVEoNR7Bfwe0khKhU33KBB-Cvxus4
Content-type: application/json

{
	"printerId":"74489420",
	"title":"Label BC",
	"contentType":"raw_base64",
	"source":"Dynamics BC Weibel",
	"content":"bW0NCnpPDQpKDQpINTAsMTAsVA0KTyBQDQpTZTswLjAwLDAuMDAsMjIwLjAwLDIyMC4wMCwzMS4yMDtXTVMgMTksMSAoRVgzMClSDQpDcywwLjAwDQpDMSwwLjAwLDAuMDANClQgMTAsMjEwLDkwLDMscHQyNTsgUC9OOiBLT01JMDAwMDAwMDAwMDAwMTAxMSAvIFJFVjogMDAwMDAwMDAwMQ0KVCAyMCwyMTAsOTAsMyxwdDI1OyBTL046IDAwMDAwMDAwMDAwMDAwMDAwMDEwIC8gT0RBOg0KQTENCg"
}



###
GET  https://api.printnode.com/printjobs/7356183274 HTTP/1.1
Authorization: Basic User:WJvzmkJLpB_PBDTVEoNR7Bfwe0khKhU33KBB-Cvxus4
###
GET  https://api.printnode.com/printjobs HTTP/1.1
Authorization: Basic User:WJvzmkJLpB_PBDTVEoNR7Bfwe0khKhU33KBB-Cvxus4
###


